version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
      - "5678:5678"
    volumes:
      - ./:/code
    command: python -m debugpy --listen 0.0.0.0:5678 -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:3
    ports:
      - "27017:27017"

  redis:
    image: redis:3
    ports:
      - "6379:6379"
